version: '3.1'

services:

  server:
    image: adgs85/gomonserver:1.0.1
    restart: always
    environment:
      DB_HOST: "postgresql.server"
    extra_hosts:
      postgresql.server: "172.17.0.1"
    ports:
      - 8080:8080
